-- Functions for KAPOTAKKHO Holdings

-- 1. GET_PROJECTS_COUNT
CREATE OR REPLACE FUNCTION GET_PROJECTS_COUNT(p_client_name IN VARCHAR2) RETURN NUMBER IS
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM projects WHERE client = p_client_name;
    RETURN v_count;
EXCEPTION WHEN OTHERS THEN RETURN 0;
END;
/

-- 2. GET_EMPLOYEE_TENURE
CREATE OR REPLACE FUNCTION GET_EMPLOYEE_TENURE(p_emp_id IN employees.id%TYPE) RETURN NUMBER IS
    v_tenure NUMBER := 0;
BEGIN
    SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, join_date) / 12) INTO v_tenure FROM employees WHERE id = p_emp_id;
    RETURN NVL(v_tenure, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
    WHEN OTHERS THEN RETURN -1;
END;
/

-- 3. GET_DEPARTMENT_HEADCOUNT
CREATE OR REPLACE FUNCTION GET_DEPARTMENT_HEADCOUNT(p_dept_name IN VARCHAR2) RETURN NUMBER IS
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM employees WHERE department = p_dept_name AND status = 'Active';
    RETURN v_count;
EXCEPTION WHEN OTHERS THEN RETURN 0;
END;
/

-- 4. GET_OPEN_JOBS_COUNT
CREATE OR REPLACE FUNCTION GET_OPEN_JOBS_COUNT RETURN NUMBER IS
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM jobs WHERE status = 'Open' AND deadline >= CURRENT_DATE;
    RETURN v_count;
EXCEPTION WHEN OTHERS THEN RETURN 0;
END;
/

-- 5. IS_VALID_EMAIL
CREATE OR REPLACE FUNCTION IS_VALID_EMAIL(p_email IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
    IF REGEXP_LIKE(p_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RETURN 'YES';
    ELSE
        RETURN 'NO';
    END IF;
END;
/
