-- Sequences for KAPOTAKKHO Holdings

-- 1. SEQ_CUSTOM_REPORT_ID
CREATE SEQUENCE SEQ_CUSTOM_REPORT_ID START WITH 1000 INCREMENT BY 1 MINVALUE 1000 NOCACHE NOCYCLE;
/

-- 2. SEQ_CONTACT_TICKET
CREATE SEQUENCE SEQ_CONTACT_TICKET START WITH 5001 INCREMENT BY 1 MINVALUE 5001 NOCACHE NOCYCLE;
/

-- 3. SEQ_EMPLOYEE_BADGE
CREATE SEQUENCE SEQ_EMPLOYEE_BADGE START WITH 2001 INCREMENT BY 1 MINVALUE 2001 NOCACHE NOCYCLE;
/
