-- Triggers for KAPOTAKKHO Holdings

-- 1. TRG_CAPITALIZE_EMP_NAME
CREATE OR REPLACE TRIGGER TRG_CAPITALIZE_EMP_NAME
BEFORE INSERT OR UPDATE OF name ON employees
FOR EACH ROW
BEGIN
    :NEW.name := INITCAP(:NEW.name);
END;
/

-- 2. TRG_PREVENT_ACTIVE_PROJ_DEL
CREATE OR REPLACE TRIGGER TRG_PREVENT_ACTIVE_PROJ_DEL
BEFORE DELETE ON projects
FOR EACH ROW
BEGIN
    IF :OLD.status = 'In Progress' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cannot delete an active project.');
    END IF;
END;
/

-- 3. TRG_SET_EMPLOYEE_TIMESTAMPS
CREATE OR REPLACE TRIGGER TRG_SET_EMPLOYEE_TIMESTAMPS
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
    IF :NEW.created_at IS NULL THEN :NEW.created_at := CURRENT_TIMESTAMP; END IF;
    IF :NEW.updated_at IS NULL THEN :NEW.updated_at := CURRENT_TIMESTAMP; END IF;
END;
/

-- 4. TRG_UPPERCASE_DEPT_CODE
CREATE OR REPLACE TRIGGER TRG_UPPERCASE_DEPT_CODE
BEFORE INSERT OR UPDATE OF code ON departments
FOR EACH ROW
BEGIN
    IF :NEW.code IS NOT NULL THEN :NEW.code := UPPER(:NEW.code); END IF;
END;
/

-- 5. TRG_LOG_PROJECT_STATUS_CHANGE
CREATE OR REPLACE TRIGGER TRG_LOG_PROJECT_STATUS_CHANGE
AFTER UPDATE OF status ON projects
FOR EACH ROW
BEGIN
    IF :OLD.status != :NEW.status THEN
        DBMS_OUTPUT.PUT_LINE('Project ' || :NEW.id || ' status changed.');
    END IF;
END;
/
