<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Report - Kapotakkhho Holdings</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Arial', sans-serif; }
        @media print {
            body { background: white; margin: 0; padding: 0; }
            .no-print { display: none; }
            .print-container { max-width: 100%; border: none; box-shadow: none; padding: 2rem; }
        }
    </style>
</head>
<body class="bg-gray-100 min-h-screen p-8" onload="window.print()">

    <div class="print-container max-w-4xl mx-auto bg-white p-10 border border-gray-200 shadow-sm rounded-lg">
        
        <!-- Header -->
        <div class="flex justify-between items-start border-b-2 border-gray-800 pb-6 mb-8">
            <div>
                <h1 class="text-4xl font-serif font-bold text-gray-900 tracking-wide">Kapotakkhho Holdings</h1>
                <p class="text-gray-600 mt-2">Executive Summary Report</p>
            </div>
            <div class="text-right text-sm text-gray-500 space-y-1">
                <p><strong>Generated By:</strong> {{ Auth::user()->name ?? 'System Admin' }}</p>
                <p><strong>Date & Time:</strong> {{ $date ?? now()->format('F d, Y h:i A') }}</p>
                <p><strong>Ref:</strong> KHL-REP-{{ strtoupper(Str::random(6)) }}</p>
            </div>
        </div>

        <!-- Content -->
        <div class="mb-10">
            <h2 class="text-xl font-bold text-gray-800 mb-4 uppercase tracking-wider border-b border-gray-200 pb-2">Key Metrics Overview</h2>
            
            <div class="grid grid-cols-3 gap-6 text-center">
                <div class="p-6 border border-gray-200 rounded-lg bg-gray-50">
                    <p class="text-sm font-semibold text-gray-500 uppercase">Total Employees</p>
                    <p class="text-4xl font-bold text-gray-900 mt-2">{{ $stats['total_employees'] ?? 0 }}</p>
                </div>
                
                <div class="p-6 border border-gray-200 rounded-lg bg-gray-50">
                    <p class="text-sm font-semibold text-gray-500 uppercase">Active Projects</p>
                    <p class="text-4xl font-bold text-gray-900 mt-2">{{ $stats['active_projects'] ?? 0 }}</p>
                </div>
                
                <div class="p-6 border border-gray-200 rounded-lg bg-gray-50">
                    <p class="text-sm font-semibold text-gray-500 uppercase">Recent Inquiries</p>
                    <p class="text-4xl font-bold text-gray-900 mt-2">{{ $stats['recent_inquiries'] ?? 0 }}</p>
                </div>
            </div>
        </div>

        <!-- Additional Text Placeholder -->
        <div class="mb-10 text-gray-700 leading-relaxed text-sm">
            <h2 class="text-xl font-bold text-gray-800 mb-4 uppercase tracking-wider border-b border-gray-200 pb-2">Operational Status</h2>
            <p class="mb-4">
                This report highlights the core operational metrics as of the generation date. Kapotakkhho Holdings Ltd. continues to maintain steady growth across all divisions.
                Active project statuses are being monitored by the PMO to ensure timely delivery and compliance with national standards.
            </p>
            <p>
                Human resource allocation is optimal. Any significant deviations in inquiry volumes have been flagged for the corporate communications team for immediate review.
            </p>
        </div>

        <!-- Signatures -->
        <div class="mt-24 pt-10 border-t border-gray-300 grid grid-cols-2 gap-10">
            <div class="text-center">
                <div class="border-b border-gray-800 w-48 mx-auto mb-2"></div>
                <p class="text-sm font-bold text-gray-800">Prepared By</p>
                <p class="text-xs text-gray-500">{{ Auth::user()->name ?? 'System Admin' }}</p>
            </div>
            <div class="text-center">
                <div class="border-b border-gray-800 w-48 mx-auto mb-2"></div>
                <p class="text-sm font-bold text-gray-800">Authorized Signature</p>
                <p class="text-xs text-gray-500">Kapotakkhho Management</p>
            </div>
        </div>

    </div>

    <!-- Print Control for screen view -->
    <div class="no-print mt-8 text-center">
        <button onclick="window.print()" class="px-6 py-2 bg-blue-600 text-white rounded shadow hover:bg-blue-700 transition">
            Print Report Now
        </button>
        <button onclick="window.close()" class="ml-4 px-6 py-2 bg-gray-300 text-gray-800 rounded shadow hover:bg-gray-400 transition">
            Close Tab
        </button>
    </div>

</body>
</html>
